New verbs and fold refactor (UI)
microsoft/data-wrangling-components pull request #70
Opened 2022-02-05 01:41 UTC by gaudyb

- React component implementation for new verbs: erase, merge, pivot and unfold
- Refactor of fold verb to receive custom names for key and value columns
- Spread fix to use custom output columns

2022-02-08 21:12 UTC, natoverse commented
* Spread component: It would help to have a label above the optional output columns to differentiate from the spread column (i.e., "New column names").
* Spread component: Editing the output columns doesn't quite work - as you type the textbox loses focus after each letter. The output is correct though.
* Spread typing: can we change the output `columns` name to `to` so it is consistent with our other verbs for output column naming (`columns` is used elsewhere for inputs, so this could be confusing).
* Can you add an example of all new verbs to the `every-operation.json` config example in the webapp, so we have examples of all new verbs

2022-02-15 22:02 UTC, natoverse requested changes

2022-02-16 01:24 UTC, gaudyb commented on packages/core/src/types.ts
> +export enum MergeStrategy {
Done

2022-02-16 01:24 UTC, gaudyb commented on packages/core/src/engine/verbs/pivot.ts
> +	const { key, value, operation } = args as PivotArgs
Done

2022-02-16 18:25 UTC, natoverse approved these changes

2022-02-16 18:54 UTC, natoverse approved these changes

2022-02-16 18:54 UTC, natoverse commented on packages/react/src/compounds/FilterAggregateLookup/FilterAggregateLookup.tsx
> +				console.log('to', to)
remove console.log

2022-02-16 18:54 UTC, natoverse commented on packages/react/src/controls/MergeInputs/MergeInputs.tsx
> +				console.log(event)
remove console.log

2022-02-16 23:24 UTC, merged